# Generated by Django 3.2 on 2023-07-12 02:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Biology1', models.CharField(max_length=100, null=True)),
                ('Biology2', models.CharField(max_length=100, null=True)),
                ('Biology3', models.CharField(max_length=100, null=True)),
                ('Biology4', models.CharField(max_length=100, null=True)),
                ('Biology5', models.CharField(max_length=100, null=True)),
                ('Biology6', models.CharField(max_length=100, null=True)),
                ('Biology7', models.CharField(max_length=100, null=True)),
                ('Biology8', models.CharField(max_length=100, null=True)),
                ('Biology9', models.CharField(max_length=100, null=True)),
                ('Biology10', models.CharField(max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.persona')),
            ],
            options={
                'verbose_name': 'biology',
                'verbose_name_plural': 'biologys',
            },
        ),
    ]
