# Generated by Django 3.2 on 2023-07-15 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='physical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Physical1', models.CharField(max_length=100, null=True)),
                ('Physical2', models.CharField(max_length=100, null=True)),
                ('Physical3', models.CharField(max_length=100, null=True)),
                ('Physical4', models.CharField(max_length=100, null=True)),
                ('Physical5', models.CharField(max_length=100, null=True)),
                ('Physical6', models.CharField(max_length=100, null=True)),
                ('Physical7', models.CharField(max_length=100, null=True)),
                ('Physical8', models.CharField(max_length=100, null=True)),
                ('Physical9', models.CharField(max_length=100, null=True)),
                ('Physical10', models.CharField(max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'physical',
                'verbose_name_plural': 'physicals',
            },
        ),
    ]
