# Generated by Django 3.2 on 2023-07-12 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='English',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('English1', models.CharField(max_length=100, null=True)),
                ('English2', models.CharField(max_length=100, null=True)),
                ('English3', models.CharField(max_length=100, null=True)),
                ('English4', models.CharField(max_length=100, null=True)),
                ('English5', models.CharField(max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.persona')),
            ],
            options={
                'verbose_name': 'ingles',
                'verbose_name_plural': 'ingless',
            },
        ),
    ]
