# Generated by Django 3.2 on 2023-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='English6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='Nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
