# Generated by Django 3.2 on 2023-07-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0002_auto_20230715_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='english',
            name='English10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='English11',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='English7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='English8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='english',
            name='English9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
