# Generated by Django 3.2 on 2023-07-12 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('History1', models.CharField(max_length=100, null=True)),
                ('History2', models.CharField(max_length=100, null=True)),
                ('History3', models.CharField(max_length=100, null=True)),
                ('History4', models.CharField(max_length=100, null=True)),
                ('History5', models.CharField(max_length=100, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='person.persona')),
            ],
            options={
                'verbose_name': 'history',
                'verbose_name_plural': 'historys',
            },
        ),
    ]
