# Generated by Django 3.2 on 2023-07-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20230715_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='History7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='History8',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
