# Generated by Django 3.2 on 2023-07-15 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chemistry',
            old_name='usuario',
            new_name='usuario_id',
        ),
    ]
