# Generated by Django 3.2 on 2023-07-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemistry', '0002_rename_usuario_chemistry_usuario_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemistry',
            name='Nombre',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
