# Generated by Django 3.2 on 2023-07-12 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matery', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matery',
            name='Nombre',
        ),
    ]
