# Generated by Django 3.2 on 2023-07-12 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matery', '0002_remove_matery_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matery',
            old_name='Orientacion1',
            new_name='Matematicas1',
        ),
        migrations.RenameField(
            model_name='matery',
            old_name='Orientacion2',
            new_name='Matematicas2',
        ),
        migrations.RenameField(
            model_name='matery',
            old_name='Orientacion3',
            new_name='Matematicas3',
        ),
        migrations.RenameField(
            model_name='matery',
            old_name='Orientacion4',
            new_name='Matematicas4',
        ),
        migrations.RenameField(
            model_name='matery',
            old_name='Orientacion5',
            new_name='Matematicas5',
        ),
    ]
