# Generated by Django 3.2 on 2023-07-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matery', '0003_auto_20230711_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='matery',
            name='Matematicas10',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matery',
            name='Matematicas6',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matery',
            name='Matematicas7',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matery',
            name='Matematicas8',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matery',
            name='Matematicas9',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
